////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2017-2019 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @file  camxiqfunctiontable.h
/// @brief IFENode class declarations
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef CAMXIQFUNCTIONTABLE_H
#define CAMXIQFUNCTIONTABLE_H

UINT32 g_customaticTriggerNumber = 0;

OEMTriggerListSet* g_pOEM1TriggerTagList = NULL;

IQOperationTable IQInterface::s_interpolationTable =
{
    IQSettingUtils::ModuleInitialize,
    IQSettingUtils::ModuleUninitialize,
    NULL,
    IQSettingUtils::DumpTriggerCondition,
    IQSettingUtils::IQSetHardwareVersion,
    ASF30Interpolation::CheckUpdateTrigger,
    ASF30Interpolation::RunInterpolation,
    ASF30Setting::CalculateHWSetting,
    BC10Interpolation::CheckUpdateTrigger,
    BC10Interpolation::RunInterpolation,
    BC10Setting::CalculateHWSetting,
    BLS12Interpolation::CheckUpdateTrigger,
    BLS12Interpolation::RunInterpolation,
    BLS12Setting::CalculateHWSetting,
    ABF40Interpolation::CheckUpdateTrigger,
    ABF40Interpolation::RunInterpolation,
    ABF40Setting::CalculateHWSetting,
    BPSGIC30Interpolation::CheckUpdateTrigger,
    BPSGIC30Interpolation::RunInterpolation,
    BPSGIC30Setting::CalculateHWSetting,
    HDR22Interpolation::CheckUpdateTrigger,
    HDR22Interpolation::RunInterpolation,
    HDR22Setting::CalculateHWSetting,
    HDR30Interpolation::CheckUpdateTrigger,
    HDR30Interpolation::RunInterpolation,
    HDR30Setting::CalculateHWSetting,
    Linearization34Interpolation::CheckUpdateTrigger,
    Linearization34Interpolation::RunInterpolation,
    Linearization34Setting::CalculateHWSetting,
    BPSPDPC20Interpolation::CheckUpdateTrigger,
    BPSPDPC20Interpolation::RunInterpolation,
    BPSPDPC20Setting::CalculateHWSetting,
    PDPC30Interpolation::CheckUpdateTrigger,
    PDPC30Interpolation::RunInterpolation,
    PDPC30Setting::CalculateHWSetting,
    CAC22Interpolation::RunInterpolation,
    CAC22Setting::CalculateHWSetting,
    CAC23Interpolation::RunInterpolation,
    CAC23Setting::CalculateHWSetting,
    CC13Interpolation::CheckUpdateTrigger,
    CC13Interpolation::RunInterpolation,
    CC13Setting::CalculateHWSetting,
    CST12Setting::CalculateHWSetting,
    CV12Interpolation::CheckUpdateTrigger,
    CV12Interpolation::RunInterpolation,
    CV12Setting::CalculateHWSetting,
    Demosaic36Interpolation::CheckUpdateTrigger,
    Demosaic36Interpolation::RunInterpolation,
    Demosaic36Setting::CalculateHWSetting,
    Demosaic37Interpolation::CheckUpdateTrigger,
    Demosaic37Interpolation::RunInterpolation,
    Demosaic37Setting::CalculateHWSetting,
    Demux13Setting::CalculateHWSetting,
    Gamma15Interpolation::CheckUpdateTrigger,
    Gamma15Interpolation::RunInterpolation,
    Gamma15Setting::CalculateHWSetting,
    Gamma16Interpolation::CheckUpdateTrigger,
    Gamma16Interpolation::RunInterpolation,
    Gamma16Setting::CalculateHWSetting,
    GRA10Interpolation::CheckUpdateTrigger,
    GRA10Interpolation::RunInterpolation,
    GRA10Setting::CalculateHWSetting,
    GTM10Interpolation::CheckUpdateTrigger,
    GTM10Interpolation::RunInterpolation,
    GTM10Setting::CalculateHWSetting,
    HNR10Interpolation::CheckUpdateTrigger,
    HNR10Interpolation::RunInterpolation,
    HNR10Setting::CalculateHWSetting,
    ICA10Interpolation::RunInterpolation,
    ICA20Interpolation::RunInterpolation,
    ICA30Interpolation::RunInterpolation,
    ICASetting::CalculateHWSetting,
    ICASetting::GetInitializationData,
    IFEABF34Interpolation::CheckUpdateTrigger,
    IFEABF34Interpolation::RunInterpolation,
    IFEABF34Setting::CalculateHWSetting,
    IFEBPCBCC50Interpolation::CheckUpdateTrigger,
    IFEBPCBCC50Interpolation::RunInterpolation,
    IFEBPCBCC50Setting::CalculateHWSetting,
    IFECC12Interpolation::CheckUpdateTrigger,
    IFECC12Interpolation::RunInterpolation,
    IFECC12Setting::CalculateHWSetting,
    IFEHDR20Interpolation::CheckUpdateTrigger,
    IFEHDR20Interpolation::RunInterpolation,
    IFEHDR20Setting::CalculateHWSetting,
    IFEHDR23Interpolation::CheckUpdateTrigger,
    IFEHDR23Interpolation::RunInterpolation,
    IFEHDR23Setting::CalculateHWSetting,
    IFELinearization33Interpolation::CheckUpdateTrigger,
    IFELinearization33Interpolation::RunInterpolation,
    IFELinearization33Setting::CalculateHWSetting,
    LSC34Interpolation::CheckUpdateTrigger,
    LSC34Interpolation::RunInterpolation,
    LSC34Setting::CalculateHWSetting,
    LSC40Interpolation::CheckUpdateTrigger,
    LSC40Interpolation::RunInterpolation,
    LSC40Setting::CalculateHWSetting,
    IFEPDPC11Interpolation::CheckUpdateTrigger,
    IFEPDPC11Interpolation::RunInterpolation,
    IFEPDPC11Setting::CalculateHWSetting,
    IPECS20Interpolation::CheckUpdateTrigger,
    IPECS20Interpolation::RunInterpolation,
    IPECS20Setting::CalculateHWSetting,
    IPETDL10Interpolation::CheckUpdateTrigger,
    IPETDL10Interpolation::RunInterpolation,
    IPETDL10Setting::CalculateHWSetting,
    Pedestal13Interpolation::CheckUpdateTrigger,
    Pedestal13Interpolation::RunInterpolation,
    Pedestal13Setting::CalculateHWSetting,
    WB12Setting::CalculateHWSetting,
    WB13Setting::CalculateHWSetting,
    SCE11Interpolation::RunInterpolation,
    SCE11Setting::CalculateHWSetting,
    TF10Interpolation::CheckUpdateTrigger,
    TF10Interpolation::RunInterpolation,
    TF10Setting::CalculateHWSetting,
    TF10Setting::GetInitializationData,
    TF20Interpolation::CheckUpdateTrigger,
    TF20Interpolation::RunInterpolation,
    TF20Setting::CalculateHWSetting,
    TF20Setting::GetInitializationData,
    ANR10Interpolation::CheckUpdateTrigger,
    ANR10Interpolation::RunInterpolation,
    ANR10Setting::CalculateHWSetting,
    ANR10Setting::GetInitializationData,
    LTM13Interpolation::CheckUpdateTrigger,
    LTM13Interpolation::RunInterpolation,
    LTM13Setting::CalculateHWSetting,
    LTM14Interpolation::CheckUpdateTrigger,
    LTM14Interpolation::RunInterpolation,
    LTM14Setting::CalculateHWSetting,
    Upscale20Interpolation::RunInterpolation,
    Upscale20Setting::CalculateHWSetting,
    Upscale12Setting::CalculateHWSetting,
    TMC10Interpolation::CheckUpdateTrigger,
    TMC10Interpolation::RunInterpolation,
    Tintless20Interpolation::RunInterpolation,
    TMC11Interpolation::CheckUpdateTrigger,
    TMC11Interpolation::RunInterpolation,
    LENR10Interpolation::CheckUpdateTrigger,
    LENR10Interpolation::RunInterpolation,
    LENR10Setting::CalculateHWSetting,
    DSX10Interpolation::CheckUpdateTrigger,
    DSX10Interpolation::RunInterpolation,
    DSX10Setting::CalculateHWSetting,
    DSX10Setting::GetInitializationData,
    TMC12Interpolation::CheckUpdateTrigger,
    TMC12Interpolation::RunInterpolation,
    CVP10Interpolation::CheckUpdateTrigger,
    CVP10Interpolation::RunInterpolation,
    CVP10Setting::CalculateHWSetting,
};

#endif // CAMXIQFUNCTIONTABLE_H
