#SNS_INTF_PRODUCTS
SNS_SYSTEM_PRODUCTS :=

#SNS_INTF_PRODUCTS_DBG
SNS_SYSTEM_PRODUCTS_DBG := UnifiedSensorTestApp
SNS_SYSTEM_PRODUCTS_DBG += UnifiedSensorTestAppService
SNS_SYSTEM_PRODUCTS_DBG += UnifiedSensorTestAppServiceManager
SNS_SYSTEM_PRODUCTS_DBG += USTAServiceManager.xml

PRODUCT_PACKAGES += $(SNS_SYSTEM_PRODUCTS)
PRODUCT_PACKAGES_DEBUG += $(SNS_SYSTEM_PRODUCTS_DBG)
