////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 2019 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// @file camxcvpproperty.h
/// @brief Define Qualcomm Technologies, Inc. CVP proprietary data for holding internal properties/events
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef CAMXCVPPROPERTY_H
#define CAMXCVPPROPERTY_H

#include "camxdefs.h"

CAMX_NAMESPACE_BEGIN

/// @brief Structure CVP Metadata
struct CVPMetaDataInternal
{
    DOUBLE  fullResTransform[9];        ///< Intermediate 3x3 Transform generated by RANSAC
    DOUBLE  coarseTransform[9];         ///< Intermediate 3x3 Transform generated by RANSAC
    INT32   fullResTransformQ16[9];     ///< Final 3x3 Transform in Q16 format
    INT32   coarseTransformQ16[9];      ///< Final 3x3 Transform in Q16 format
    UINT32  fullResWidth;               ///< Full resoltion width
    UINT32  fullResHeight;              ///< FULL resolution height
    UINT32  processedWidth;             ///< Processed Width
    UINT32  processedHeight;            ///< Processed Height
    UINT32  nIsValid;                   ///< Flag to indicate validity
    UINT32  nFrameSumGradient;          ///< Frame-Level Sum Gradient
    UINT32  nFrameSumSquareGradient1;   ///< Frame-Level Sum Square Gradient1
    UINT32  nFrameSumSquareGradient2;   ///< Frame-Level Sum Square Gradient2
    UINT16  nLumaHist[8];               ///< Luma Histogram
    INT32   nMVxSum;                    ///< cumulative sum of MVx
    INT32   nMVySum;                    ///< cumulative sum of MVy
    UINT32  nNumMVs;                    ///< NumMVs
    UINT32  nVersionNum;                ///< Version number
    INT32   nTransformConfidence;       ///< Ransac Transform confidence
};

static const UINT32 CVPTransform_method                           = 1;
static const UINT32 CVPChromatix_enable                           = 1;
static const UINT32 CVPEnable_transform_confidence                = 1;
static const UINT32 CVPTransform_confidence_mapping_base          = 100;
static const UINT32 CVPTransform_confidence_mapping_c1            = 100;
static const UINT32 CVPTransform_confidence_mapping_c2            = 255;
static const UINT32 CVPTransform_confidence_thr_to_force_identity = 128;

CAMX_NAMESPACE_END

#endif // CAMXCVPPROPERTY_H