#SNS_INTF_VENDOR_PRODUCTS
SNS_INTF_VENDOR_PRODUCTS := libsnsdiaglog
SNS_INTF_VENDOR_PRODUCTS += libssc
SNS_INTF_VENDOR_PRODUCTS += libsnsapi
SNS_INTF_VENDOR_PRODUCTS += libsensorslog
SNS_INTF_VENDOR_PRODUCTS += libsns_low_lat_stream_stub
SNS_INTF_VENDOR_PRODUCTS += libsns_low_lat_stream_skel
SNS_INTF_VENDOR_PRODUCTS += libsns_device_mode_stub
SNS_INTF_VENDOR_PRODUCTS += libsns_device_mode_skel
SNS_INTF_VENDOR_PRODUCTS += libsns_fastRPC_util


#SNS_INTF_VENDOR_PRODUCTS_DBG
SNS_INTF_VENDOR_PRODUCTS_DBG := libsensor_low_lat
SNS_INTF_VENDOR_PRODUCTS_DBG += libUSTANative
SNS_INTF_VENDOR_PRODUCTS_DBG += libSensorCalLibNative

PRODUCT_PACKAGES += $(SNS_INTF_VENDOR_PRODUCTS)
PRODUCT_PACKAGES_DEBUG += $(SNS_INTF_VENDOR_PRODUCTS_DBG)
